
export const INCREASE = 'INCREASE'
export const DECREASE = 'DECREASE'
export const ADD_SHIPMENTS = 'ADD_SHIPMENTS'
export const REFRESH_CHECKED_LIST = 'REFRESH_CHECKED_LIST'
export const REMOVE_FROM_CHECKED_LIST = 'REMOVE_FROM_CHECKED_LIST'